import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import hero from '../assets/hero1.svg'
import VDSCard from "../components/main/VDSCard";
import {useState} from "react";
import {classNames} from "../utils/utils";
import Link from "next/link";

export default function Home() {
  const[open, setOpen] = useState(false);
    return (
        <div className={styles.container}>
            <Head>
                <title>MicroHost</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div>
                <nav className="px-2 sm:px-4 py-2.5">
                    <div className="container flex flex-wrap justify-between items-center mx-auto">
                        <a href="https://flowbite.com/" className="flex items-center">
                            <img src="" className="mr-3 h-6 sm:h-9"
                                 alt="Logo"/>
                            <span
                                className="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">MicroHost</span>
                        </a>
                        <button data-collapse-toggle="navbar-default" type="button"
                                className="inline-flex items-center p-2 ml-3 text-sm rounded-lg md:hidden focus:outline-none focus:ring-2 text-gray-400 hover:bg-gray-700 focus:ring-gray-600"
                                aria-controls="navbar-default" aria-expanded="false"
                        onClick={() => setOpen(!open)}>
                            <span className="sr-only">Открыть</span>
                            <svg className="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path fillRule="evenodd"
                                      d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                                      clipRule="evenodd"></path>
                            </svg>
                        </button>
                        <div className={classNames(open ? "" : "hidden", "w-full md:block md:w-auto")}>
                            <ul className="flex flex-col p-4 mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
                                <li>
                                    <a href="#"
                                       className="block py-2 pr-4 pl-3 text-white rounded md:bg-transparent md:p-0 md:text-lg"
                                    >Главная</a>
                                </li>
                                <li>
                                    <a href="#"
                                       className="block py-2 pr-4 pl-3 text-white rounded md:bg-transparent md:p-0 md:text-lg">
                                        О нас</a>
                                </li>
                                <li>
                                    <a href="#"
                                       className="block py-2 pr-4 pl-3 text-white rounded md:bg-transparent md:p-0 md:text-lg">
                                        Тарифы</a>
                                </li>
                                <li>
                                    <a href="#"
                                       className="block py-2 pr-4 pl-3 text-white rounded md:bg-transparent md:p-0 md:text-lg">
                                        Мониторинг</a>
                                </li>
                            </ul>
                        </div>
                        <div className={classNames(open ? "" : "hidden", "w-full md:block md:w-auto")}>
                            <Link href={"/billing"}
                                    className="md:ml-0 ml-4 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg md:text-lg px-5 py-2.5 mr-2 mb-2 bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-blue-800">Биллинг
                            </Link>
                        </div>
                    </div>
                </nav>
                <div className="container mx-auto md:pt-24">
                    <div className="mx-auto md:w-2/3">
                        <div className="text-center md:text-4xl text-2xl font-bold">
                            Лучший облачный хостинг
                            для любых задач
                        </div>
                        <Image src={hero} alt={"hero"} width={1000} height={500} className="md:w-2/4 mx-auto mt-4"/>
                    </div>
                    <div className="pt-12">
                        <div className="text-center text-4xl font-bold">
                            Наши услуги
                        </div>
                        <div className="mt-4 bg-zinc-800 mx-auto">
                            <div className="p-4 mx-auto">
                                <div className="text-center md:text-4xl text-2xl mb-4">
                                    Виртуальные сервера
                                </div>
                                <div className="text-center md:text-2xl text-xl">
                                    Мощные процессоры, низкий пинг и низкие цены!
                                </div>
                                <div className="text-center md:text-lg text-base mt-4 md:w-2/3 mx-auto">
                                    Наши тарифы подойдут под множество задач,
                                    начиная от сайтов 1C-Битрикс, заканчивая
                                    большими игровыми серверами.
                                </div>
                                <div className="md:w-2/3 mx-auto">
                                    <div className="flex md:w-3/4 mt-12 mb-4 md:flex-row flex-col">
                                        <div
                                            className="border focus:outline-none font-medium rounded-lg text-sm px-5 py-2.5 mr-2 md:mb-2 mb-6 text-white border-white mr-6 md:w-max w-full">Виртуализация
                                            KVM
                                        </div>
                                        <div
                                            className="border focus:outline-none font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 text-white border-white md:w-max w-full">Процессоры
                                            от 4.9 ГГц
                                        </div>
                                    </div>
                                    <div
                                        className="border focus:outline-none font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 text-white border-white md:w-max w-full">
                                        Низкий пинг
                                    </div>
                                    <div className="mt-6 text-center">
                                        от 380 руб/мес
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="text-center text-3xl font-bold mt-12">
                        Тарифы
                    </div>
                    <div className="text-center text-xl mt-4">Процессор - Intel Xeon E5-2667v2</div>
                    <div className="[&>*]:mt-4">
                        <VDSCard/>
                        <VDSCard/>
                        <VDSCard/>
                        <VDSCard/>
                    </div>
                    <div className="text-center text-3xl font-bold mt-12">
                        Почему мы?
                    </div>
                    <div className="grid md:grid-cols-2 gap-x-8 place-items-stretch gap-y-4 mt-12 mx-auto">
                        <div className="bg-zinc-800 mx-auto p-4 rounded w-full">
                            <div className="font-bold md:text-xl text-lg">
                                Быстрая поддержка
                            </div>
                            <div className="md:text-lg text-sm md:mt-0 mt-2">
                                Мы готовы предоставить Вам самую
                                качественую и бесплатную
                                поддержку. Установим ПО,
                                поможем с настройкой!
                            </div>
                        </div>
                        <div className="bg-zinc-800 mx-auto p-4 rounded w-full">
                            <div className="font-bold md:text-xl text-lg">
                                Высокий Uptime
                            </div>
                            <div className="md:text-lg text-sm md:mt-0 mt-2">
                                Мы максимально прикладываем
                                усилия, чтобы держать сервис на высоте.
                                Поэтому аптайм наших серверов - 99.983%
                            </div>
                        </div>
                        <div className="bg-zinc-800 mx-auto p-4 rounded w-full">
                            <div className="font-bold md:text-xl text-lg">
                                Низкий пинг
                            </div>
                            <div className="md:text-lg text-sm md:mt-0 mt-2">
                                Мы распологаемся в дате-центре
                                ММТС-9 в Москве.
                            </div>
                        </div>
                        <div className="bg-zinc-800 mx-auto p-4 rounded w-full">
                            <div className="font-bold md:text-xl text-lg">
                                Низкие цены
                            </div>
                            <div className="md:text-lg text-sm md:mt-0 mt-2">
                                У нас одни из самых минимальных цен на рынке.
                            </div>
                        </div>
                    </div>
                    <div className="text-center text-3xl font-bold mt-12">
                        Остались вопросы?
                    </div>
                    <div className="text-center text-lg mt-4 md:w-1/3 mx-auto">
                        Если у Вас остались вопросы - смело пишите в
                        нашу группу Вконтакте, мы с радостью отметим
                        на любые Ваши вопрсоcы.
                    </div>
                    <footer className="p-4 sm:p-6 mt-24">
                        <div className="md:flex md:justify-between">
                            <div className="mb-6 md:mb-0">
                                <div className="flex flex-col">
                                    <a href="https://flowbite.com/" className="flex items-center">
                                        <img src="" className="mr-3 h-8"
                                             alt="Microhost Logo"/>
                                        <span
                                            className="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">MicroHost</span>
                                    </a>
                                    <span className="text-sm text-gray-500 dark:text-gray-400 mt-4">© 2022 MicroHost
                          </span>
                                    <span className="text-sm text-gray-500 dark:text-gray-400 mt-4">Кого-то ИП
                          </span>
                                    <span className="text-sm text-gray-500 dark:text-gray-400 mt-4">Почта для обращений:
                          </span>
                                    <span className="text-sm text-gray-500 dark:text-gray-400">support@microhost.ru
                          </span>
                                </div>
                            </div>
                            <div>
                                <h2 className="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Услуги</h2>
                                <ul className="text-gray-600 dark:text-gray-400">
                                    <li className="mb-4">
                                        <a href="https://flowbite.com/" className="hover:underline">VDS Low</a>
                                    </li>
                                    <li className="mb-4">
                                        <a href="https://tailwindcss.com/" className="hover:underline">VDS High</a>
                                    </li>
                                </ul>
                            </div>
                            <div>
                                <h2 className="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Полезные
                                    ссылки</h2>
                                <ul className="text-gray-600 dark:text-gray-400">
                                    <li className="mb-4">
                                        <a href="https://github.com/themesberg/flowbite"
                                           className="hover:underline ">Условия пользования</a>
                                    </li>
                                    <li className="mb-4">
                                        <a href="https://discord.gg/4eeurUVvTy" className="hover:underline">Политика
                                            конфиденциальности</a>
                                    </li>
                                    <li className="mb-4">
                                        <a href="https://discord.gg/4eeurUVvTy" className="hover:underline">Группа
                                            ВКонтакте</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </footer>
                </div>
            </div>
        </div>
    );
}
